# Generated by Django 2.2.7 on 2019-11-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='like_genre_users', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, related_name='like_movie_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Message'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
